### DISCUSSION TITLE
Weird GPIO button behavior

### DISCUSSION THREAD

**Discussion by oliboss** [MiczFlor/RPi-Jukebox-RFID#2406] [Q&A]
Hi all, 

So far I got the phoniebox setup with a RPI HiFi AMP HAT TAS5713 Amplifier Audio Module and a USB RFID reader (after having trouble connecting another one to the GPIO pins). 

I removed rpgpio from the venv and replaced it by lgpio (per the advice [here](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2405)). The gpio.yml is pretty simple:

```
pin_factory:
  type: rpigpio.RPiGPIOFactory
input_devices:
  TogglePlayback:
    type: Button
    kwargs:
      pin: 17
    actions:
      on_press:
        alias: toggle
```
I am using the GPIO headers on the sound board. 

When I connect GPIO 17 and Ground directly with a screwdriver the play/pause toggle works as expected. 

However as soon as I connect any kind of cable to GPIO 17 (even without connecting it to anything but thin air) the player starts to osciallate between play and pause state. 

Any idea where to start the bug hunt? I tried to add a `hold_time` of 0.5 to the button - which did not changed anything. 

Best regrads
Oli

**Comment by AlvinSchiller** [comment]
In your config you still use the `rpigpio` factory.
Have you tried changing this to ` lgpio.LGPIOFactory`, like described in the linked thread?

**Comment by oliboss** [comment]
@AlvinSchiller 

I have uninstalled rpigpio and installed lgpio:

```
systemctl --user stop jukebox-daemon
source .venv/bin/activate
pip uninstall rpi-gpio
pip install rpi-lgpio
systemctl --user start jukebox-daemon
```
I also tried alternative factories in `gpio.yml`:

```
pin_factory:
#  type: rpigpio.RPiGPIOFactory
  type: lgpio.LGPIOFactory
```
... which does not change the behavior at all. 

When I close the button then it actually plays the song without jittering / oscillation. 

To my understanding the GPIOs are digital inputs so there should not be a threshold issue. It feels however as if the GPIO would be activated by some noise and a state that should be LOW is sometimes read as HIGH.

**Comment by oliboss** [comment]
After quite some fiddling around I think I found a way to get it working - although not fully sure if this is how the button is intended to work. 

I connected the button to pin GPIO_17 and 3V3 (external 1kΩ resistor). When I then modify the gpio.yml like so:

```yaml
pin_factory:
  type: lgpio.LGPIOFactory
input_devices:
  TogglePlayback:
    type: Button
    kwargs:
      pin: 17
      pull_up: 
      active_state: true
    actions:
      on_press:
        alias: toggle
```
 the button works as expected. Note that the pull_up is intentionally set to none to disable it.
