### DISCUSSION TITLE
Need help with Button configuration

### DISCUSSION THREAD

**Discussion by oliboss** [MiczFlor/RPi-Jukebox-RFID#2430] [Q&A]
I have 1 Switch (that toggles between on and off) and two buttons connected to my phoniebox (RPI HiFi AMP HAT TAS5713 Amplifier Audio Module and a USB RFID reader). The elements are connected to 3.3V and via a 1k pullup to GPIO 17,27 and 22.

The gpio.yaml looks as follow:

```yaml
pin_factory:
  type: lgpio.LGPIOFactory
input_devices:
  TogglePlayback:
    type: Switch
    kwargs:
      pin: 17
      pull_up: 
      active_state: true
    actions:
      on_press:
        alias: toggle
  NextSong:
    type: Button
    kwargs:
      pin: 27
      pull_up: 
      active_state: true
    actions:
      on_press:
        alias: next_song
  PreviousSong:
    type: Button
    kwargs:
      pin: 22
      pull_up: 
      active_state: false
    actions:
      on_press:
        alias: prev_song
```
The switch implementation is the one I described [here](https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2408#discussioncomment-10234245). 

I checked with a separate Python program that all the elements switch from 0 to 1 and the state change is detected by the raspberry.

When I only have the switch configuration in the file it works but as soon as I add the buttons the setup stops working. 

The three devices are logged in the logfile:

```
18.09.2024 12:08:02 -  620:plugs.py           - jb.plugin            - MainThread      - DEBUG    - Package load finalizer: calling gpio.finalize()
18.09.2024 12:08:02 -  203:__init__.py        - jb.gpioz             - MainThread      - DEBUG    - Create input device 'TogglePlayback', type='Switch', config={'type': 'Switch', 'kwargs': {'pin': 17, 'pull_up': None, 'active_state': True}, 'actions': {'on_press': {'alias': 'toggle'}}}
18.09.2024 12:08:02 -   59:input_devices.py   - jb.gpioz             - MainThread      - DEBUG    - Set RPC for 'TogglePlayback.on_press': player.ctrl.toggle()
18.09.2024 12:08:02 -  203:__init__.py        - jb.gpioz             - MainThread      - DEBUG    - Create input device 'NextSong', type='Button', config={'type': 'Button', 'kwargs': {'pin': 27, 'pull_up': None, 'active_state': True}, 'actions': {'on_press': {'alias': 'next_song'}}}
18.09.2024 12:08:02 -   59:input_devices.py   - jb.gpioz             - MainThread      - DEBUG    - Set RPC for 'NextSong.on_press': player.ctrl.next()
18.09.2024 12:08:02 -  203:__init__.py        - jb.gpioz             - MainThread      - DEBUG    - Create input device 'PreviousSong', type='Button', config={'type': 'Button', 'kwargs': {'pin': 22, 'pull_up': None, 'active_state': False}, 'actions': {'on_press': {'alias': 'prev_song'}}}
18.09.2024 12:08:02 -   59:input_devices.py   - jb.gpioz             - MainThread      - DEBUG    - Set RPC for 'PreviousSong.on_press': player.ctrl.prev()
```

I have experimented quite a bit but it seems that I am missing a point here. Any help appreciated!

Best regards
Oliver
