### DISCUSSION TITLE
Issus with Shutdown Button

### DISCUSSION THREAD

**Discussion by Gen-Chan** [MiczFlor/RPi-Jukebox-RFID#2481] [Q&A] [answered]
Hey there,
I build a jukebox with RFID and Hardware Buttons. After some minor mistakes on my own. I ended with mostly everything working fine. The last reaming issue is the shutdown button. I have no Idea why there is no function on in. Can someone give me a hand by tracking down the problem?

My setup is a Pi 3B with future3/main installed as described in the docs
As RFID I use an RDM6300 wired to GPIO
I have 4 Hardware Buttons wired to GPIO with a 1kOhm resistor
Also, I have connected KY-040 rotary Encoder for the volume control with a 1kOhm resistor.
For the audio output, I use the onboard audio interface with a USB powered active stereo speaker. 
my gpio.yaml file looks like this:
```
in_factory:
  type: rpigpio.RPiGPIOFactory

input_devices:
  Shutdown:
    type: LongPressButton
    kwargs:
      pin: 3
      hold_time: 3
    actions:
      on_press:
        alias: shutdown

  PreviousSong:
    type: Button
    kwargs:
      pin: 22
      hold_time: 0.5
    actions:
      on_press:
        alias: prev_song

  TogglePlayback:
    type: Button
    kwargs:
      pin: 27
      hold_time: 0.5
    actions:
      on_press:
        alias: toggle

  NextSong:
    type: Button
    kwargs:
      pin: 23
      hold_time: 0.5
    actions:
      on_press:
        alias: next_song

  VolumeRotator:
    type: RotaryEncoder
    kwargs:
      a: 5
      b: 6
    actions:
      on_rotate_clockwise:
        alias: change_volume
        args: 2
      on_rotate_counter_clockwise:
        alias: change_volume
        args: -2

  ButtonRotator:
    type: Button
    kwargs:
      pin: 17
      hold_time: 0.5
    actions:
      on_press:
        alias: none
```
All buttons are physically working. I have switched the physical wires from the buttons of GPIO 3 and 27, the hardware button I'm willing to use for shutdown now points to toggle and works fine. 
I also looked at the logs/error.log but its empty.
If I can give some other information, please tell me what do you need to know.
Thanks for your time and you will to help.
